services:
  db:
    image: postgres:17
    container_name: upforschool_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: upforschool
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data_upforschool

volumes:
  db_data: